# Copyright (C) 2025 Ian Torres <iantorres@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: /srv/build

    strategy:
      fail-fast: false
      matrix:
        version: [1.87.0, 1.88.0, 1.89.0, 1.90.0]
        type: [debug, release]
        link: [shared, static]

    container:
      image: ghcr.io/anexperimentwithtime/compiler:${{ matrix.version }}-${{ matrix.type }}-${{ matrix.link }}

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: state_password
          MYSQL_USER: user
          MYSQL_PASSWORD: state_password
          MYSQL_DATABASE: state
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check format
        run: |
          bash scripts/check-format.sh

      - name: Prepares databases
        env:
          DB_HOST: mysql
          DB_PORT: 3306
        run: |
          bash scripts/prepare-database.sh

      - name: Run build and test
        env:
          DB_HOST: mysql
          DB_USER: user
          DB_PASSWORD: state_password
          DB_NAME: state
          DB_PORT: 3306
        run: |
          bash scripts/build-and-test.sh ${{ matrix.type }} ${{ matrix.link }}